ALTER TABLE Playlist DROP CONSTRAINT FK_Library_Playlist;
ALTER TABLE "User" DROP CONSTRAINT FK_Library_User;
ALTER TABLE PlaylistSong DROP CONSTRAINT FK_Playlist_PlaylistSong;
ALTER TABLE Song DROP CONSTRAINT FK_Song_Library;
ALTER TABLE PlaylistSong DROP CONSTRAINT FK_Song_PlaylistSong;
ALTER TABLE Song DROP CONSTRAINT FK_Song_SongTag;
ALTER TABLE SongTag DROP CONSTRAINT FK_SongTag_Genre;

DROP TABLE Genre IF EXISTS;
DROP TABLE Library IF EXISTS;
DROP TABLE Playlist IF EXISTS;
DROP TABLE PlaylistSong IF EXISTS;
DROP TABLE Song IF EXISTS;
DROP TABLE SongTag IF EXISTS;
DROP TABLE "User" IF EXISTS;
